### ISSUE TITLE
Q menu doesn't work

### ISSUE THREAD

**Issue by fedorissimo** [Mee12345/GMod-Infinite-Map#66] opened 2022-12-13 06:04 UTC
Sometimes far away from the original map I just can't take weapons... Or anything else. If I return or die, nothing changes. I have to reload the map.

**Comment by Mee12345** [comment] 2022-12-13 13:09
Duplicate of https://github.com/Mee12345/GMod-Infinite-Map/issues/56

**Closed by Mee12345** 2022-12-13 13:09 UTC
