### ISSUE TITLE
Hands work strange

### ISSUE THREAD

**Issue by fedorissimo** [Mee12345/GMod-Infinite-Map#68] opened 2022-12-13 06:19 UTC
Something far away from spawn first person hands just disappear on any weapons. It gets OK later.

**Comment by Mee12345** [comment] 2022-12-13 13:06
have you checked addon conflictions?

**Comment by fedorissimo** [comment] 2022-12-13 14:58
I checked addon issues and didn't find anything like this

**Comment by fedorissimo** [comment] 2022-12-13 15:01
I'm not a guru in english, but WHAT IS WRONG

**Comment by fedorissimo** [comment] 2022-12-13 15:01
Everything is red

**Comment by Mee12345** [comment] 2022-12-13 15:38
not seeing any errors doesnt mean there isnt an addon that is conflicting, disable all addons and see if the issue persists

on an unrelated note when is the last time you updated? this bug should have been patched already

**Comment by fedorissimo** [comment] 2022-12-13 16:24
I didn't play for some days, but it wasn't really old version. I can't check it now, but I want to make a piracy GMOD virsion with lots of addons to play with my friends, so I will test it there. (I have 70GB addons, it's impossible to disable all of them))

**Comment by Mee12345** [comment] 2022-12-13 17:59
> 70 gb of addons
> impossible to disable all of them
mate I think its probably an addon confliction

**Comment by fedorissimo** [comment] 2022-12-14 13:14
> > 70 gb of addons
> > impossible to disable all of them
> 
> mate I think its probably an addon confliction

Lots of them are jojo models and stupid maps

**Comment by Mee12345** [comment] 2022-12-14 20:17
I cant reproduce the bug so closing for now

**Closed by Mee12345** 2022-12-14 20:17 UTC
