### ISSUE TITLE
make wiremod water sensor work better

### ISSUE THREAD

**Issue by LucasAiden** [Mee12345/gmod-infinite-map#113] opened 2023-02-02 20:50 UTC
so wiremod ships and sea monsters work better

**Comment by LucasAiden** [comment] 2023-02-02 20:51
the sensor dosent detect water

**Comment by xCeezyx** [comment] 2023-02-03 02:29
Thats because the water in the mod is fake water not source water

**Comment by LucasAiden** [comment] 2023-02-04 15:28
but its eazy to fix it, like:
if sensor.y < water_level then
   sensor.out = true
else
   sensor.out = false
end

**Comment by Mee12345** [comment] 2023-02-08 19:52
feel free to add it urself, the code is open source
the reason im not doing it because it would make the code messier

**Comment by Mee12345** [comment] 2023-02-08 19:54
duplicate of https://github.com/Mee12345/gmod-infinite-map/issues/81

**Closed by Mee12345** 2023-02-08 19:54 UTC
Labels: duplicate, enhancement
